### ISSUE TITLE
Import "side-menu-item.js" from "side-menu"

### ISSUE THREAD

**Issue by jogibear9988** [gero1992/side-menu#2]
could you add an import of "side-menu-item.js" to "side-menu.js", or link in the npm to a js file wich imports all your files?
With such a change, your package would be directly usable in my designer: https://node-projects.github.io/web-component-designer-demo/index.html
Without that my designer could not know what to import.

**Comment by jogibear9988** [comment]
And maybe it would be possible to switch to new LIT version, cause it has breaking changes, and mixing NPMs is problematic.

**Comment by jogibear9988** [comment]
fixed by #3

**Comment by gero1992** [comment]
I just published the new version.
Will update all dependencies on the weekend and will close the issue afterwards.
Thanks again for the contribution 🍻

**Comment by gero1992** [comment]
@jogibear9988 I just migrated to `lit 3` and published the new version
